# -*- coding: utf-8 -*-
"""ai lecture.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1b97ZTFA-uZIWK1onNUKPqQqwfgu1bo4N

libraries
"""

pip install -U langchain-google-genai

pip show langchain-google-genai

!pip install google-generativeai python-pptx PyMuPDF

"""key

"""

from google.colab import userdata
GEMINI_API_KEY=userdata.get('GEMINI_API_KEY')

"""upload file

"""

from google.colab import files

uploaded = files.upload()
file_name = list(uploaded.keys())[0]

"""extract text from ppt"""

from pptx import Presentation

def extract_text_from_ppt(file_path):
    prs = Presentation(file_path)
    text = ""

    for slide in prs.slides:
        for shape in slide.shapes:
            if hasattr(shape, "text"):
                text += shape.text + "\n"

    return text

ppt_text = extract_text_from_ppt(file_name)
print("Extracted Text Preview:\n", ppt_text[:1000])

import fitz  # PyMuPDF

def extract_text_from_pdf(file_path):
    doc = fitz.open(file_path)
    text = ""

    for page in doc:
        text += page.get_text()

    return text

# If PDF:
# ppt_text = extract_text_from_pdf(file_name)

"""ai doubt solver"""

from langchain_google_genai import ChatGoogleGenerativeAI
from langchain_core.messages import HumanMessage

model=ChatGoogleGenerativeAI( model="gemini-2.5-flash",api_key =GEMINI_API_KEY )

def ask_question(context, question):
    prompt = f"""
You are an AI tutor.

Explain the following lecture content in a simple way for students.

Lecture Content:
{context}

Student Question:
{question}

Answer in very simple words with examples if possible.
"""

    response = model.invoke([HumanMessage(content=prompt)])
    return response.content

"""ask question"""

print("\n🎓 AI Lecture Doubt Solver Ready!")
print("Type 'exit' to stop.\n")

while True:
    question = input("Ask your question: ")

    if question.lower() == "exit":
        break

    answer = ask_question(ppt_text, question)
    print("\n🤖 Answer:\n", answer, "\n")